// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: api_keys.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, name, key_hash, scopes, is_active, last_used_at, created_at FROM api_keys WHERE key_hash = $1 AND is_active = TRUE
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

type ListApiKeysRow struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	IsActive   *bool      `json:"is_active"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  *time.Time `json:"created_at"`
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, scopes, is_active, last_used_at, created_at FROM api_keys ORDER BY created_at DESC
`

func (q *Queries) ListApiKeys(ctx context.Context) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysRow{}
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (name, key_hash, scopes) VALUES ($1, $2, $3) RETURNING id, name, key_hash, scopes, is_active, last_used_at, created_at
`

type CreateApiKeyParams struct {
	Name    string   `json:"name"`
	KeyHash string   `json:"key_hash"`
	Scopes  []string `json:"scopes"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey, arg.Name, arg.KeyHash, arg.Scopes)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateLastUsed = `-- name: UpdateLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastUsed, id)
	return err
}

const revokeApiKey = `-- name: RevokeApiKey :exec
UPDATE api_keys SET is_active = FALSE WHERE id = $1
`

func (q *Queries) RevokeApiKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeApiKey, id)
	return err
}
