FROM golang:1.25-alpine AS builder

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.24

COPY --from=builder /go/bin/goose /usr/local/bin/goose

COPY db/migrations /migrations

ENTRYPOINT ["goose", "-dir", "/migrations", "postgres"]
